name: Test Auth

on: pull_request:
  paths:
    - 'tickets/auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Auth test
        working-directory: ./tickets/auth
        run: |
          npm install && npm run test:ci
